version: "3"

services:
  image_processing:
    container_name: image_processing
    build:
      context: .
      args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - PASSWORD=${PASSWORD}
        - UID=${UID}
        - GID=${GID}
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - CUDA_VERSION=${CUDA_VERSION}
      dockerfile: Dockerfile
    image: n622jwith/image_processing:latest
    # ホストの22番ポートは使用できないので、10000番ポートを使用する(22にアクセスするとkey errorが発生する)
    ports:
      - "10001:22"
    # これは必要ないかもしれない
    platform: "linux/amd64"
    environment:
      - DISPLAY=${DISPLAY}
      - "QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority/:/home/${USER_NAME}/.Xauthority:ro
      - $HOME/.ssh:/home/${USER_NAME}/.ssh:ro
    hostname: image_processing
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
    user: "${UID}:${GID}"
